- .circleci/config.yml
Added version 4 and changed branch names
> Fix CircleCI Testflight job

- src/App.js
- src/components/settings/SettingsBackup.js
- src/components/settings/SettingsLanguageSelector.js
- src/screens/Receive.js
- src/services/HarvestingService.js
- src/services/TransactionService.js
- src/store/harvesting.js
- src/store/network.js
- src/store/settings.js
- src/utils/DataSchemaMigrations.js
- src/utils/storage/AsyncCache.js
Solved:
- #5 
- #11 
- #8  
- #16 
- #38 
- #3
> P1 and P3 Bug fixes

- src/locales/i18n.js
- src/locales/translations/es.json
- src/locales/translations/ja.json
- src/locales/translations/zh.json
- src/screens/Harvest.js
- When missing translation, english one is used
- Added spanish, chinese and japanese
- Removed harvesting image screen when not enough balance
> Improved translations

- env/default.json.example
- package.json
- src/components/controls/Input.js
- src/components/organisms/TableView.js
- src/config/fees.js
- src/locales/translations/en.json
- src/screens/AccountDetails.js
- src/screens/AddContact.js
- src/screens/Send.js
- src/screens/Sidebar.js
- src/services/NetworkService.js
- src/services/TransactionService.js
- src/storage/models/NetworkModel.js
- src/store/transfer.js
- yarn.lock
- Updated to new testnet
- Added dynamic fees calculation
- Fixed:
#64 
#76  
#75 
#27
> New testnet update and bugfixing

- ios/SymbolWallet.xcodeproj/project.pbxproj
- src/components/controls/Checkbox.js
- src/components/molecules/ConfirmModal/index.js
- src/components/organisms/PluginList.js
- src/components/organisms/TableView.js
- src/components/organisms/transaction/AggregateTransaction.js
- src/components/organisms/transaction/TransferTransaction.js
- src/components/settings/SettingsLogout.js
- src/locales/translations/en.json
- src/locales/translations/ja.json
- src/screens/AddContact.js
- src/screens/Home.js
- src/screens/Passcode/Passcode.styl
- src/screens/Send.js
- src/screens/ShowMnemonics/ShowMnemonics.styl
- src/services/AccountService.js
- src/services/ListenerService.js
- src/services/TransactionService.js
- src/store/account.js
- src/store/transfer.js
- src/store/wallet.js
Resolved: #94 
Resolved: #96 
Resolved: #97 
Resolved: #98 
Resolved: #79
Resolved: #74
Resolved: #89
Resolved: #4
Resolved: #57
Resolved: #87
Resolved: #43
Resolved: #69
Resolved: #97
Resolved: #75
Resolved: #36
> Bug fixing minors

- src/App.js
- src/components/organisms/WizardStepView.js
- src/locales/translations/en.json
- src/screens/ShowQRCode/index.js
- src/screens/Sidebar.js
- src/utils/donwload.js
Resolved: #13
Resolved: #71
Resolved: #72
Need to retest #81
> iOS bug fixes

- env/default.json.example
- src/Router.js
- src/components/organisms/TableView.js
- src/locales/translations/en.json
- src/screens/Harvest.js
- src/screens/LinkedKeysDetails.js
- src/services/HarvestingService.js
- src/services/TransactionService.js
- src/storage/models/HarvestingModel.js
- src/storage/persistence/HarvestingSecureStorage.js
- src/store/harvesting.js
resolves #29 ,
resolves #77 ,
resolves #103 ,  
Default node is now us-west-1
> Harvesting refactored

- src/screens/Send.js
> add number check to the amount input

- src/screens/Send.js
> Fixed send amount formatter

- src/components/controls/CopyView.js
- src/components/controls/InputAddress.js
- src/locales/translations/en.json
- src/screens/QRScanner.js
- src/utils/donwload.js
> replace hardcoded strings with translations

- src/locales/translations/en.json
- src/screens/AddContact.js
- Resolved #79
- Resolved #106
> Address book fixes

- src/screens/Harvest.js
- src/services/HarvestingService.js
> Fixed node public key for harvesting

- src/components/controls/Checkbox.js
- src/components/organisms/transaction/TransferTransaction.js
- src/locales/translations/en.json
- src/locales/translations/es.json
- src/locales/translations/it.json
- src/locales/translations/ja.json
- src/locales/translations/ru.json
- src/locales/translations/zh.json
- src/screens/AccountDetails.js
- src/screens/Send.js
- src/services/FetchTransactionService.js
- src/services/HarvestingService.js
Resolved #136 
Resolved #134 
Resolved #114
> Fixes and translations

- src/screens/ConfirmTransaction.js
> Fix fee delimeter

- src/Router.js
- src/components/organisms/SymbolGradientContainer.js
- src/screens/Passcode/index.js
1. Fixed the Navigation doesn't work on some devices bug
- Unable to accept terms
- Unable to access the home screen after entering the PIN
2. Added dark gradient schema
> Fix the navigation router bug. Add new gradient schema

- package.json
- src/services/ListenerService.js
- src/utils/commonHelpers.js
- yarn.lock
- Added function to re-open listener when closed event emitted
- Updated symbol-sdk
> Resolved #164 Transaction listener doesn't work

- src/screens/LinkedKeysDetails.js
Resolved #169 wrong linked keys
> Inconsistent linked keys

- env/default.json.example
update explorer and faucet url
> fix: update link

- CHANGELOG.md
- package-lock.json
- package.json
- Fix behavior when node is down and application crashes[#259](https://github.com/symbol/mobile-wallet/issues/259)
- Fix fees selector problems when recipient address is not provided [#254](https://github.com/symbol/mobile-wallet/issues/254)
- Updated CI/CD pipeline
- Build Android version against SDK version30
> adding changelogs for version 1.0.4

- CHANGELOG.md
- package.json
- yarn.lock
* symbol-sdk version is upgraded to `v1.0.3`
* package version is updated to `1.4.1`
* changelog is updated
> hotfix/sdk upgrade 1.0.3

- .github/dependabot.yaml
- .github/workflows/auto-merge.yaml
- .github/workflows/codeql-analysis.yaml
problem: dependencies are not auto update
solution: enable Dependabot to check for updates weekly
enable CodeQL analysis
> [wallet/mobile] fix: enable Dependabot automerge
